name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🔧 Install Vercel CLI
        run: npm install --global vercel

      - name: 🚀 Deploy to Vercel
        run: |
          if [[ "$GITHUB_REF_NAME" == "main" ]]; then
            vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --confirm
          else
            vercel --yes --token=${{ secrets.VERCEL_TOKEN }} --confirm
          fi
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
